# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aug.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\taug.proto\x12\x05proto\"\x18\n\nIdResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x1e\n\x0f\x41ugmentResponse\x12\x0b\n\x03\x65rr\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2a\n\x11TemplateAugmentor\x12%\n\x02Id\x12\x0c.proto.Empty\x1a\x11.proto.IdResponse\x12%\n\x07\x41ugment\x12\x0c.proto.Empty\x1a\x0c.proto.EmptyB\tZ\x07./protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aug_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007./proto'
  _IDRESPONSE._serialized_start=20
  _IDRESPONSE._serialized_end=44
  _AUGMENTRESPONSE._serialized_start=46
  _AUGMENTRESPONSE._serialized_end=76
  _EMPTY._serialized_start=78
  _EMPTY._serialized_end=85
  _TEMPLATEAUGMENTOR._serialized_start=87
  _TEMPLATEAUGMENTOR._serialized_end=184
# @@protoc_insertion_point(module_scope)
