# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
    push:
        paths:
            - "**.go"
            - ".github/workflows/ci.yml"
            - "go.mod"
            - "go.sum"
        branches: ["main"]
    pull_request:
        paths:
            - "**.go"
            - ".github/workflows/ci.yml"
            - "go.mod"
            - "go.sum"
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  #   current Node LTS
                  node-version: "18.13.0"

            - name: Debug
              run: |
                  yarn -v
                  ls -l

            - name: Debug script
              run: |
                  yarn init
                  yarn add -D tailwindcss

            - name: Debug 2
              run: |
                  mkdir test-dir
                  DEBUG_WORKING_DIR=$(pwd)/test-dir
                  yarn --cwd $DEBUG_WORKING_DIR init -y
                  yarn --cwd $DEBUG_WORKING_DIR add -D tailwindcss

            - name: Build
              run: go build -v ./...

            - name: Run unit tests.
              # Ignores smoketests: go list ./... | grep -v /smoketests/
              run: go test $(go list ./... | grep -v /smoketests/)
